### ISSUE TITLE
NullPointerException in com.datarank.tempest.allocator.model.ModelBalancer.evaluateBalance

### ISSUE THREAD

**Issue by cerelisa** [datarank/tempest#20]
I am deploying a new Elasticsearch image which contains the Tempest plugin in my cluster:

1.  Shutdown the cluster
2.  Deployed 3 ES master nodes

I am getting the following NullPointerException on the master node and the other master nodes cannot connect to it:

[2016-03-07 18:38:08,997][ERROR][discovery.zen            ] [ibm-aug5-elasticsearch-master-wikxwmhl] unexpected failure during [zen-disco-join (elected_as_master)]
java.lang.NullPointerException
        at com.datarank.tempest.allocator.model.ModelBalancer.evaluateBalance(ModelBalancer.java:78)
        at com.datarank.tempest.allocator.LocalMinimumShardsAllocator.rebalance(LocalMinimumShardsAllocator.java:136)
        at org.elasticsearch.cluster.routing.allocation.allocator.ShardsAllocators.rebalance(ShardsAllocators.java:81)
        at org.elasticsearch.cluster.routing.allocation.AllocationService.reroute(AllocationService.java:190)
        at org.elasticsearch.cluster.routing.allocation.AllocationService.reroute(AllocationService.java:161)
        at org.elasticsearch.cluster.routing.allocation.AllocationService.reroute(AllocationService.java:147)
        at org.elasticsearch.discovery.zen.ZenDiscovery$3.execute(ZenDiscovery.java:388)
        at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:374)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:196)
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:162)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
[2016-03-07 18:38:12,005][INFO ][com.datarank.tempest.allocator.LocalMinimumShardsAllocator] [ibm-aug5-elasticsearch-master-wikxwmhl] Rebalancing.

**Comment by cerelisa** [comment]
Just want to add this this is using the 1.0.0 version installed from here (which looks like the latest release)

https://github.com/datarank/tempest/releases

**Comment by aewhite** [comment]
We'll need to know the version of ES too. They have changed a lot since 1.x days.

**Comment by cerelisa** [comment]
This is ES 1.7.1, but we may also be interested in using Tempest in an 2.x environment.  Is that also supported?

I see that there may have been a hot fix for this:  https://github.com/datarank/tempest/commit/b3231a98a5665bfec6a61df2af8bf6a9807a161e

How can I install that fix?  

Thanks!

**Comment by aewhite** [comment]
Fixed in 2.x which has been back ported to ES 1.x
